Add Bitergia branding to Kibiter 6.8.6
grimoirelab/kibiter pull request #126
Opened 2020-03-09 19:14 UTC by dlumbrer

This commit has the feature of adding the branding of Bitergia to the Kibiter 6.8.6 version, the same that in 6.1.4, logo, colors and text changed.

This video shows the branding:

![Peek 2020-03-09 20-11](https://user-images.githubusercontent.com/9249232/76248901-9081a300-6242-11ea-8586-38b5b7a86371.gif)

2020-03-09 19:42 UTC, GeorgLink commented
It looks amazing 🤩

2020-03-10 08:10 UTC, sduenas commented on src/ui/public/chrome/_variables.scss
> +$kbnChromeGlobalNavBackground: #333;
Shouldn't be better to use 6 digit numbers?

2020-03-10 09:21 UTC, dlumbrer commented
PR updated @sduenas , thanks!

2020-03-10 09:43 UTC, sduenas requested changes
All looks good but just fix a minor problem.

2020-03-10 09:43 UTC, sduenas commented on src/ui/public/assets/favicons/browserconfig.xml
> +</browserconfig>
Add an empty line after this.

2020-03-10 10:02 UTC, dlumbrer commented on src/ui/public/assets/favicons/browserconfig.xml
> +</browserconfig>
Done!

2020-03-10 10:02 UTC, dlumbrer commented
Updated, thanks @sduenas

2020-03-10 10:10 UTC, sduenas approved these changes
LGTM

2020-03-10 10:11 UTC, merged