[docker] Add Dockerfile and docker_entrypoint files for 6.8.6
grimoirelab/kibiter pull request #133
Opened 2020-03-16 17:25 UTC by dlumbrer

This commit adds the needed files for the image creation process of the 6.8.6 Kibiter secured version. For Bitergia purposes.

2020-03-17 09:52 UTC, sduenas requested changes
Would you mind to add a README file with the env variables you defined and how to use them? Please also check my other comment about the dockerfile.

2020-03-17 09:52 UTC, sduenas commented on docker/Dockerfile
> +RUN apt-get update && \
Do you think it makes sense to have all the installation in the same step? I think it will be better to split it in several parts to improve the speed in case the image fails in this step.

2020-03-17 11:24 UTC, dlumbrer commented on docker/Dockerfile
> +RUN apt-get update && \
I agree, thanks!

2020-03-17 12:12 UTC, dlumbrer commented
Updates @sduenas, thanks

2020-03-17 18:26 UTC, sduenas requested changes
LGTM but I found the next error building the image:

```
Step 25/30 : RUN ./opt/kibana/bin/kibana | sleep 200 > /tmp/run_kibana_log.txt
 ---> Running in 4af05fbcda26
Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`


events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite (net.js:782:14)
Emitted 'error' event at:
    at Socket.onerror (_stream_readable.js:691:12)
    at Socket.emit (events.js:194:15)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:11:34)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite (net.js:784:10)
```

2020-03-17 18:44 UTC, sduenas reviewed
While running the container I also found the next error, so the container fails before it starts:

```
kibiter_1        | /docker_entrypoint.sh: line 67: syntax error: unexpected end of file
```
This is part of the docker-compose I use to run the container:
```
kibiter:
  restart: on-failure:5
  image: integration-6.8.6
  environment:
    - PROJECT_NAME=Development
    - NODE_OPTIONS=--max-old-space-size=1000
    - ELASTICSEARCH_URL=https://admin:admin@elasticsearch:9200
    - ELASTICSEARCH_USER=admin
    - ELASTICSEARCH_PASSWORD=admin
  links:
    - elasticsearch
  ports:
    - 5601:5601

```

2020-03-17 21:55 UTC, dlumbrer commented
> LGTM but I found the next error building the image:
> 
> ```
> Step 25/30 : RUN ./opt/kibana/bin/kibana | sleep 200 > /tmp/run_kibana_log.txt
>  ---> Running in 4af05fbcda26
> Browserslist: caniuse-lite is outdated. Please run next command `npm update caniuse-lite browserslist`
> 
> 
> events.js:174
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: write EPIPE
>     at WriteWrap.afterWrite (net.js:782:14)
> Emitted 'error' event at:
>     at Socket.onerror (_stream_readable.js:691:12)
>     at Socket.emit (events.js:194:15)
>     at onwriteError (_stream_writable.js:431:12)
>     at onwrite (_stream_writable.js:456:5)
>     at _destroy (internal/streams/destroy.js:40:7)
>     at Socket.dummyDestroy [as _destroy] (internal/process/stdio.js:11:34)
>     at Socket.destroy (internal/streams/destroy.js:32:8)
>     at WriteWrap.afterWrite (net.js:784:10)
> ```

This is a "controlled" error because we force to init Kibiter in the image creation process, forcing Kibiter to bundle its scripts (optimize process) and then launching the next time instantly. The error appears because we "kill" Kibiter.


 

> While running the container I also found the next error, so the container fails before it starts:
> 
> ```
> kibiter_1        | /docker_entrypoint.sh: line 67: syntax error: unexpected end of file
> ```
> 
> This is part of the docker-compose I use to run the container:
> 
> ```
> kibiter:
>   restart: on-failure:5
>   image: integration-6.8.6
>   environment:
>     - PROJECT_NAME=Development
>     - NODE_OPTIONS=--max-old-space-size=1000
>     - ELASTICSEARCH_URL=https://admin:admin@elasticsearch:9200
>     - ELASTICSEARCH_USER=admin
>     - ELASTICSEARCH_PASSWORD=admin
>   links:
>     - elasticsearch
>   ports:
>     - 5601:5601
> ```

I solve it, I added by mistake an "else" instead of a "fi", sorry about that

2020-03-18 12:19 UTC, sduenas reviewed
Tested. It works perfectly. You can merge it.

2020-03-18 12:21 UTC, merged